### ISSUE TITLE
Error when attempting to access manual

### ISSUE THREAD

**Issue by ristevskin** [LBC-Iriarte/SLFinder#2]
Hello,

When I try to read your manual, I get this error:

"Error rendering embedded code

Invalid PDF"

Could you please fix this?
N

**Comment by J-Calvelo** [comment]
Hello,
Unfortunatelly I cannot reproduce the issue. If I download the repository I can open it with Foxit PDF Feader and Google Chrome. Same if I just click it on the github page. What software are you using?

**Comment by ristevskin** [comment]
Hello, 
I was trying to access it via the GitHub page.

**Comment by J-Calvelo** [comment]
Well in that case I've no idea. This is how it looks on my computer

<img width="937" alt="image" src="https://github.com/user-attachments/assets/1fb2ea24-74de-4bc7-b758-11718f8d6d74">

Try downloading this file. Is the same PDF that I downladed and printed again as PDF. All text and insertions should be a simple image now

[SL_Finder_Manual_reprint_to_pdf.pdf](https://github.com/user-attachments/files/17564260/SL_Finder_Manual_reprint_to_pdf.pdf)

**Comment by ristevskin** [comment]
Thank you, that works!
